Repository team-i-Five/code_Data-collect, pull requests merged in 2023-11, with the labels that each got.

#10 인터파크, 티켓링크 뮤지컬 랭킹 크롤링
  code/Test.ipynb
  code/Test2.ipynb
  code/Test6_get_detail.ipynb
  code/rank_Test1.ipynb
  code/rank_interpart_ticketlink.ipynb
Labels: enhancement, help wanted

#12 airflow dag file
  .gitignore
  code/Test7-1_rank_interpark_ticketlink.ipynb
  code/Test7-2_rank_yes24.ipynb
  code/Test7_rank.ipynb
  code/Test8-1get_interpark.py
  code/Test8_rank_to_localdb.ipynb
Labels: enhancement

#14 0.5.0/save init ranking table data
  code/Production2_insert_ranking_db.ipynb
Labels: enhancement

#16 0.5.2/airflow docker image
  airflow_docker/Dockerfile
  airflow_docker/dags/Production3_get_rank.py
  airflow_docker/requirements.txt
  code/Production3_get_rank.py
  code/Test8-1get_interpark.py
Labels: enhancement, good first issue
